//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucNangPhanMem
    {
        public ChucNangPhanMem()
        {
            this.VaiTro_ChucNangPhanMem = new HashSet<VaiTro_ChucNangPhanMem>();
        }
    
        public string ID { get; set; }
        public string TenChucNang { get; set; }
        public string MoTa { get; set; }
        public string TenForm { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual ICollection<VaiTro_ChucNangPhanMem> VaiTro_ChucNangPhanMem { get; set; }
    }
}
