//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhatKyHeThong
    {
        public NhatKyHeThong()
        {
            this.NguoiDungs = new HashSet<NguoiDung>();
        }
    
        public string ID { get; set; }
        public string MoTa { get; set; }
        public string HanhDongID { get; set; }
        public string FormName { get; set; }
        public string NguoiTao { get; set; }
    
        public virtual ICollection<NguoiDung> NguoiDungs { get; set; }
    }
}
