//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaiTro
    {
        public VaiTro()
        {
            this.NguoiDungs = new HashSet<NguoiDung>();
            this.VaiTro_ChucNangPhanMem = new HashSet<VaiTro_ChucNangPhanMem>();
        }
    
        public string IDVaiTro { get; set; }
        public string TenVaiTro { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<NguoiDung> NguoiDungs { get; set; }
        public virtual ICollection<VaiTro_ChucNangPhanMem> VaiTro_ChucNangPhanMem { get; set; }
    }
}
